// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9PMNZqo_iTn_ko3B2FR55lEnrotOCT_o',
    appId: '1:103324410405:web:5ca101903daec5590ed5cc',
    messagingSenderId: '103324410405',
    projectId: 'chat-app-3654c',
    authDomain: 'chat-app-3654c.firebaseapp.com',
    storageBucket: 'chat-app-3654c.appspot.com',
    measurementId: 'G-SZV92QMM6V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgT0c8CTfPr7ArEoFxbCVjWPHqBZKS6hw',
    appId: '1:103324410405:android:6d884e48d83e41300ed5cc',
    messagingSenderId: '103324410405',
    projectId: 'chat-app-3654c',
    storageBucket: 'chat-app-3654c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnr2hlNPtGxwa5BnsSA44OCwxQ62V11IU',
    appId: '1:103324410405:ios:06d0ca6a5b1449340ed5cc',
    messagingSenderId: '103324410405',
    projectId: 'chat-app-3654c',
    storageBucket: 'chat-app-3654c.appspot.com',
    iosBundleId: 'com.example.bug_away',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnr2hlNPtGxwa5BnsSA44OCwxQ62V11IU',
    appId: '1:103324410405:ios:06d0ca6a5b1449340ed5cc',
    messagingSenderId: '103324410405',
    projectId: 'chat-app-3654c',
    storageBucket: 'chat-app-3654c.appspot.com',
    iosBundleId: 'com.example.bug_away',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9PMNZqo_iTn_ko3B2FR55lEnrotOCT_o',
    appId: '1:103324410405:web:dbb0586900b6f8620ed5cc',
    messagingSenderId: '103324410405',
    projectId: 'chat-app-3654c',
    authDomain: 'chat-app-3654c.firebaseapp.com',
    storageBucket: 'chat-app-3654c.appspot.com',
    measurementId: 'G-52MLDGR16E',
  );
}
